import os


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


RABBITMQ_URL = os.getenv("RABBITMQ_URL")
RABBITMQ_DOCUMENT_QUEUE = os.getenv("RABBITMQ_DOCUMENT_PROCESS_QUEUE")
RABBITMQ_PROCESSING_RESULT_QUEUE = os.getenv("RABBITMQ_DOCUMENT_RESULT_QUEUE")

ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST")
ELASTICSEARCH_INDEX = os.getenv("ELASTICSEARCH_INDEX")


AWS_S3_ACCESS_KEY = os.getenv("AWS_S3_ACCESS_KEY")
AWS_S3_SECRET_KEY = os.getenv("AWS_S3_SECRET_KEY")
AWS_S3_REGION = os.getenv("AWS_S3_REGION")

SENTENCE_TRANSFORMER_MODEL_NAME = os.getenv("SENTENCE_TRANSFORMER_MODEL_NAME")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL_NAME = os.getenv("GEMINI_MODEL_NAME")
SUMMARIZE_PROMPT_VERSION = os.getenv("SUMMARIZE_PROMPT_VERSION")

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
MLFLOW_REGISTERED_MODEL_NAME = os.getenv("MLFLOW_REGISTERED_MODEL_NAME")
MLFLOW_SUMMARIZE_MODEL_URI = f"models:/{MLFLOW_REGISTERED_MODEL_NAME}@champion"

OCR_USE_GPU = _env_bool("OCR_USE_GPU", False)
