import os


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


RABBITMQ_URL = os.getenv("RABBITMQ_URL")
RABBITMQ_DOCUMENT_QUEUE = os.getenv("RABBITMQ_DOCUMENT_PROCESS_QUEUE")
RABBITMQ_PROCESSING_RESULT_QUEUE = os.getenv("RABBITMQ_DOCUMENT_RESULT_QUEUE")

ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST")
ELASTICSEARCH_INDEX = os.getenv("ELASTICSEARCH_INDEX")


R2_ACCESS_KEY = os.getenv("R2_ACCESS_KEY")
R2_SECRET_KEY = os.getenv("R2_SECRET_KEY")
R2_REGION = os.getenv("R2_REGION", "auto")
R2_ENDPOINT = os.getenv("R2_ENDPOINT")

SENTENCE_TRANSFORMER_MODEL_NAME = os.getenv("SENTENCE_TRANSFORMER_MODEL_NAME")

REDIS_URL = os.getenv("REDIS_URL")
REDIS_SOCKET_TIMEOUT = float(os.getenv("REDIS_SOCKET_TIMEOUT", "0.2"))
REDIS_CONNECT_TIMEOUT = float(os.getenv("REDIS_CONNECT_TIMEOUT", "0.2"))
QUERY_EMBEDDING_CACHE_TTL = int(os.getenv("QUERY_EMBEDDING_CACHE_TTL", "21600"))

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL_NAME = os.getenv("OLLAMA_MODEL_NAME")
OLLAMA_TIMEOUT = float(os.getenv("OLLAMA_TIMEOUT", "300"))
OLLAMA_MAX_INPUT_CHARS = int(os.getenv("OLLAMA_MAX_INPUT_CHARS", "6000"))
OLLAMA_NUM_CTX = int(os.getenv("OLLAMA_NUM_CTX", "8192"))
OLLAMA_NUM_PREDICT = int(os.getenv("OLLAMA_NUM_PREDICT", "768"))
OLLAMA_KEEP_ALIVE = os.getenv("OLLAMA_KEEP_ALIVE", "30m")

RAG_RETRIEVE_SIZE = int(os.getenv("RAG_RETRIEVE_SIZE", "10"))
RAG_TOP_CHUNKS = int(os.getenv("RAG_TOP_CHUNKS", "5"))
RAG_WINDOW_WORDS = int(os.getenv("RAG_WINDOW_WORDS", "150"))
RAG_MAX_PASSAGES = int(os.getenv("RAG_MAX_PASSAGES", "5"))
RAG_CONTEXT_CHARS = int(os.getenv("RAG_CONTEXT_CHARS", "6500"))
RAG_MIN_SIMILARITY = float(os.getenv("RAG_MIN_SIMILARITY", "0.25"))
RAG_MAX_QUESTION_CHARS = int(os.getenv("RAG_MAX_QUESTION_CHARS", "500"))

SUMMARIZE_PROMPT_VERSION = os.getenv("SUMMARIZE_PROMPT_VERSION")

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
MLFLOW_REGISTERED_MODEL_NAME = os.getenv("MLFLOW_REGISTERED_MODEL_NAME")
MLFLOW_SUMMARIZE_MODEL_URI = f"models:/{MLFLOW_REGISTERED_MODEL_NAME}@champion"

OCR_USE_GPU = _env_bool("OCR_USE_GPU", False)

PROCESSOR_API_KEY = os.getenv("PROCESSOR_API_KEY")
